#!/bin/sh

set -e

# we expect a directory named 'gitlab-ci-build' and we build a docker image
# named/tagged by the subdirectory name (may be xxx:yyy) for each subdirectory

cd colpari-gitlab-images

for DIR in *
do
	echo "building '$DIR'"
	ls -la "$DIR/"
	cd "$DIR"
	docker build --pull -t "$CI_REGISTRY_IMAGE/$DIR" .
	docker push "$CI_REGISTRY_IMAGE/$DIR"
	cd - >/dev/null
done
